<?php
/**
 * Copyright 2024 Adobe
 * All Rights Reserved.
 */
?>
<div id="tfa-auth-container" data-bind="scope:'tfa-auth'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<?= $block->getChildHtml('change-provider') ?>

<script type="text/x-magento-init">
{
    "#tfa-auth-container": {
        "Magento_TwoFactorAuth/js/duo/api": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
